[tool.poetry]
name = "xboinc"
version = "0.0.1"
description = "Xsuite BOINC interface"
homepage = "https://github.com/xsuite/xboinc"
repository = "https://github.com/xsuite/xboinc"
authors = [
           "Frederik F. Van der Veken <frederik@cern.ch>",
           "Davide Di Croce <davide.di.croce@cern.ch>",
           "Giovanni Iadorala <giovanni.iadorala@cern.ch>"
]
readme = "README.md"
license = "Apache 2.0"
include = [ "LICENSE", "NOTICE" ]


[tool.poetry.dependencies]
python = ">=3.8"
numpy
xobjects
xdeps
xpart
xtrack
xcoll
xfields

[tool.poetry.dev-dependencies]
pytest = ">7"

[build-system]
# Needed for pip install -e (BTW: need pip version 22)
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api